import type { Metadata } from 'next'
import '@/app/styles/globals.css'
import { ReactNode } from 'react'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode
}>) {
    return (
        <html lang="ru">
            <body className="p-4">{children}</body>
        </html>
    )
}
